name: release 

on:
  push:
    branches:
      - master
    paths:
      - 'update.json'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get commit message
      id: commit_msg
      run: |
        COMMIT_MSG=$(git log -1 --pretty=%s -- update.json | tr -d '\n')
        echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV

    - name: Read update.json
      id: setup
      run: |
        ZIP_URL=$(jq -r .zipUrl update.json)
        ZIP_NAME=$(basename "$ZIP_URL")
        echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
        echo "ZIP_URL=$ZIP_URL" >> $GITHUB_ENV

    - name: Create dummy zip
      run: |
        cd module/dummy_zip
        zip -r dummy.zip *
        mv dummy.zip ../

    - name: Create module zip
      run: |
        cd module
        zip -r "$ZIP_NAME" *

    - name: Create Draft GitHub Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: "${{ env.COMMIT_MSG }}"
        name: "${{ env.COMMIT_MSG }}"
        body: "See changelog for details."
        draft: true
        files: "module/${{ env.ZIP_NAME }}" 
